server:
  applicationConnectors:
  - type: http
    port: 50051
  adminConnectors:
  - type: http
    port: 50151

printingPort: 50052
packagingPort: 50053

printingHost: "127.0.0.1"
packagingHost: "127.0.0.1"

applicationTagsYamlFile: "./styling/applicationTags.yaml"
wfReportingConfigYamlFile: "./wfReportingConfig.yaml"